/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:98b301e1-f87f-48d0-b634-2535b26b2d39",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_gZosXJFrR",
    "aws_user_pools_web_client_id": "5uakd49hmec2ilu9kpm27oj5bi",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "highernotes",
            "endpoint": "https://n8apxfe58l.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://hz5n2uem2nd23mwkmet3hpnihe.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_user_files_s3_bucket": "highernotes04a4eafc2aba4418ab0a4f7fc4d5e0ed183144-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
